name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/docs.yaml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-15
          - macos-latest
          - windows-latest
        bazel: ['7.x', '8.x']
        include:
          - os: ubuntu-latest
            name: Linux x86_64
          - os: ubuntu-24.04-arm
            name: Linux ARM64
          - os: macos-15
            name: macOS x86_64
          - os: macos-latest
            name: macOS ARM64
          - os: windows-latest
            name: Windows x86_64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }} (Bazel ${{ matrix.bazel }})
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel }}
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: bazel test //test/... --verbose_failures --test_output=all
      - name: Run examples
        run: cd examples && bazel test //basic:all //blas:all --verbose_failures --test_output=all
      - name: Build wasm32 targets
        run: cd examples && bazel build //wasm:hello_wasm //wasm:full_wasm --verbose_failures
      - name: Run wasm32 tests
        run: |
          node examples/bazel-bin/wasm/hello_cc.js
          node examples/bazel-bin/wasm/full.js